### ISSUE TITLE
Summer FOSSFam Meetup

### ISSUE THREAD

**Issue by Nolski** [FOSSRIT/tasks#100]
# Summary

Hey y'all, we were discussing in IRC about having a dinner meet up. Tentatively on Thursday June 13th. I'm open to dinner spot suggestions as well!

# Details

**Date**: Thursday June 13th, 6:00pm EST
**Location**: Tully's Good Times : https://goo.gl/maps/h8ab7Nh6APorhiZc8

**Comment by ct-martin** [comment]
I'm free then. If anyone will be coming from near campus I'd appreciate if I could hitch a ride. Also open to suggestions for places to go.

**Comment by ct-martin** [comment]
Also, ping to @xforever1313 and @whenbellstoll

**Comment by thenaterhood** [comment]
Yes

**Comment by jibby0** [comment]
I'm terrible about checking email :( Sadly I'm busy tomorrow, til like 7. But y'all have fun!

**Comment by Nolski** [comment]
I'm also happy to reschedule this to Monday night as well!

**Comment by xforever1313** [comment]
We could do Tulley's, they are famous for their chicken fingers, and they are delicious: https://www.tullysgoodtimes.com/food-menu/

**Comment by Nolski** [comment]
Let's do Tulley's at 6pm (I believe @ritjoe has to leave a bit early. I'll have the updated info in the original issue text.

**Comment by whenbellstoll** [comment]
I'll be there tonight

**Comment by Nolski** [comment]
Meetup Successful! Was nice seeing y'all

**Comment by jwflory** [comment]
Got any meet-up pics as proof? :wink:

**Comment by Nolski** [comment]
I believe @ct-martin does!

**Comment by ct-martin** [comment]
I do, but I can't upload it right now. It's also in backscroll in chat. SJ had to leave early but everyone else is in it
