### ISSUE TITLE
Confirm location booking for Election Night Hackathon

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#101]
# Summary

Confirm room booking with IGM for Election Night Hackathon

# Background

After 2-3 weeks into the semester, @itprofjacobs should open a conversation with IGM about booking rooms in the MAGIC Center for Tuesday, November 5th from 5:30pm to 11pm.

Once the room is confirmed, we can move faster on outreach, promotion, and seek out potential collaborations to build this event out.

# Details

It is a process to request these rooms, so it is better to start the booking conversation earlier than later.

# Outcome

* Confirmed location for Election Night Hackathon 2019

**Comment by jwflory** [comment]
@itprofjacobs To confirm, is the room reservation for the MAGIC Center in place for Tuesday, November 5th, 5:30pm to 10pm?

**Comment by itprofjacobs** [comment]
Well there is a reservation, but its for the wrong date.  Gimme a couple minutes 😊

**Comment by jwflory** [comment]
@itprofjacobs Thanks!

For reference, our confirmed booking is on Tuesday, Nov. 5th between 17:00-23:59 in rooms MSS-2150/2175. If these are the shared labs, fire code limits ~62 total people in the labs at once.

Closing this as complete. :ocean:
