### ISSUE TITLE
Add FOSS@MAGIC credit card to shared Namecheap account

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#110]
# Summary

Set up auto-renewal of `fossrit.community` and `teleirc.com` domains on shared FOSS@MAGIC Namecheap account

# Background

Today I created a Namecheap account with the new `@rit.edu` email address for FOSS. I transferred the domains `fossrit.community` and `teleirc.com` to the new account and added my personal account as a manager.

Now that the account is created, it would be great to add the billing information and set up auto-renewals so we don't have to worry about things like this sneaking up on us in the future.

# Details

Either @itprofjacobs or Brenda will need to log into the account and add the RIT-associated credit card. I can set up auto-renewal once it's added.

The `fossrit.community` expires on 2025-01-08 so we won't have anything to pay for a while there. The `teleirc.com` domain expires on 2020-05-07 so we will be billed something around $15 for another year. Optionally, we can throw a few more years onto it if that is more convenient.

# Outcome

Improve overall sustainability of our acquired domains by setting up automatic renewal with RIT-owned payment credentials

**Comment by jwflory** [comment]
Marking ticket as blocked for now. Will follow up when I am in Rochester between Feb. 10-13.

**Comment by Tjzabel** [comment]
I could potentially take a look at doing this. What would be the best way to get in contact with Brenda to do this?

**Comment by jwflory** [comment]
@Tjzabel In person at the MAGIC Suite.

I can pass you the credentials to the Namecheap account. You will also need to share this with Brenda, but I prefer to do it offline instead of emailing it out over plaintext. Once she is signed in, you will need to walk her through where to add the billing info for the MAGIC credit card.

Is there a preferred time between 9am - 3pm between Monday and Friday for you? I can facilitate this over email once I know a good time for you.

**Comment by Tjzabel** [comment]
@jwflory woops, just getting around to this now. I can take care of this after spring break. If you'd like, you can send me an encrypted email with `BCF88DA26C612113`, or on Signal/Telegram.

**Comment by jwflory** [comment]
I sent the shared Namecheap account credentials to @Tjzabel over Signal today. I also sent an email to Brenda and SJ for context. Hopefully this can get knocked out next week after spring break.
