### ISSUE TITLE
Collecting works about FOSS that have freely redistributable licensing

### ISSUE THREAD

**Issue by ritjoe** [FOSSRIT/tasks#111]
I've been meaning to make two changes to the open educational resources (OER, or just "resources") used in the HFOSS course:

1) Retain any that are freely-licensed but otherwise replace and extend the collection with content that is only freely licensed.

2) Pull the resources out of the hfoss repository into a repository that can be developed cooperatively and shared amongst the courses. 

To that end, I've pulled together several things already and have them ready to submit via a PR, which is to follow ....

**Comment by jwflory** [comment]
I moved this from an archived git repo because I wasn't sure if it was still relevant in 2020. I'm going to tentatively close this issue for now since it is over two years old, but if there is a specific thing to discuss, we can re-open again.

Closing. :clapper:
