### ISSUE TITLE
Create list of outreach opportunities for other groups on campus

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#14]
When we talked with @spotrh at lunch a few weeks ago, we had a lot of great discussion about the FOSS@MAGIC program and ways we might be able to build it up further by expanding its reach to other groups on campus, even ones that might not traditionally have a FOSS angle. Some of the ideas in this issue are from this talk.
# Creating a list

I think the best way to start is to have some creative brainstorming with other FOSSBoxers, @schneidy, and possibly interested alumni about groups that we may be able to reach out to and engage with in new ways with free and open source software. Even if some of the ideas are more far-reaching and ambitious, I think having a list of ideas to go to for these kinds of things might be a useful resource.
## Existing possibilities

I have two potential ways we could expand our outreach, one based on our talk with spot, another from a student involved with FOSS activities at RIT. With some more brainstorming, I think we can expand the ones we have below as well as build it further.
### Musical festival

This was the idea spot had. The gist is that there are a lot of music communities on campus, such as the Student Music Association (sp?) and there is an electronic music lovers club. These kinds of communities interact with a lot of different media, whether it is student content or other content found online.

Some kind of music festival could be planned where students remix others' work under Creative Commons licensing, and the work would be available for others to also take and modify to their own tastes. Planning such a thing would take a lot of effort, but I think it's a good idea of something that isn't necessarily "software" but still fits into the FOSS@MAGIC umbrella.

@itprofjacobs might be able to add thoughts to this one specifically about the logistics (again, this is a far-reaching one but is a good example for getting gears turning).
### EGSRIT LAN website

Something already under development is the Electronic Gaming Society of RIT's (EGS) new and upcoming LAN (Local Area Network) party website. The LAN site is the hub for activities that happen at a LAN, whether it's sharing announcements, posting contest results, communicating with other attendees, and more. The project can be found at [EGSRIT/LanSite](https://github.com/EGSRIT/LanSite) and is currently under development.

With more time as the site progresses, I think we could consider having a greater role within EGS. I'm particularly interested in this one too, as MAGIC does a lot of game development. If students are releasing FOSS games, partnering up with EGS in some form to make these games available and more publicized to students might be a powerful and engaging tool. I think that they are just beginning their adventure into open source with the recent LAN site, and there is a lot of potential for open source to be something that benefits their entire club.

This is one that will require some sitting and waiting for the right time to engage, but again, it's worth mentioning now to put it on the table.
# Planning this out

These are some conversation primers and starters, and either once we're all back on campus _or_ remotely over the summer, we could try to get started on coming up with a list of other ideas to increase our outreach on campus.

Anyone else have some thoughts they want to add in? Or maybe logistics of how we want to go about planning this?

**Comment by schneidy** [comment]
I think we need think bigger and reach out to a much wider audience. Think design, animation, engineering, science. FOSS can tag into so many other sections of the campus. I'm working on putting a list of possible partnerships and ideas to bounce off of people and see if there is any interest. Will be sure to post them here soonish.

**Comment by itprofjacobs** [comment]
Tom and I had several meetings with orgs on campus when he was here and Dan and I are working on a kind of master list for a lot of things.  I’d love to have to have your thoughts as well and then discuss a bunch of things in those hangout sessions.

**Comment by itprofjacobs** [comment]
What’s happening as far as “in-reach” to other programs is gonna be a lot of my job next year.

At the “top-down” level we’re looking at doing a monthly speaker series with each month with each one targeted to a different college
I’ll be meeting with many of the departments at department meetings on campus throughout the year.

Vectors for cross promotion to normally unallied departments…

1.  All of our Hackathon events, especially Space Apps.  There were a lot of Design, etc challenges this year and while they won’t be exactly the same for next year we can start talking to clubs, etc about it in the semester before to prep the way.
2.  I’m scheduling a call with EFF in the next week or two.  I’m looking at FOSS@MAGIC being the org for this but I need to understand more about it.
https://www.eff.org/deeplinks/2016/03/launching-efa <https://www.eff.org/deeplinks/2016/03/launching-efa>

**Comment by ritjoe** [comment]
Following up on the EFA link there, I find this list of allies 

https://www.eff.org/electronic-frontier-alliance/allies

useful.

First, it indicates what peer efforts are in place elsewhere. Second, it reminds us by way of example of the kinds of groups and structures are natural inreach or outreach opportunities locally. 

Most obvious to me is seeing hackerspaces on there and being reminded of our connections to [Interlock](http://www.interlockroc.org). A cryptoparty group is on there, [2600](http://www.rochester2600.com/) and Interlock have hosted at least one cryptoparty and could probably stand to do more. 

Many of the groups on that list are registered student groups: [RITLUG](https://github.com/RITLUG) is probably the most closely allied student group right now to FOSSRIT and we should continue to cultivate that assiduously.

**Comment by jwflory** [comment]
Since the last activity in this ticket was almost three years ago, I am going to close this ticket as out of scope. Most of this work was around on-going initiatives when there was a full-time staff member working on tasks like these.

If we want to reconsider, we should open a new ticket with more concrete suggestions of how to proceed.

**Comment by ritjoe** [comment]
On Thu, Mar 21, 2019 at 03:34:36PM +0000, Justin W. Flory wrote:
> Since the last activity in this ticket was almost three years ago, I am going
> to close this ticket as out of scope. Most of this work was around on-going
> initiatives when there was a full-time staff member working on tasks like
> these.

Prudence demands a certain amount of circumspection in discussing other groups and other people, particularly as concerns how responsive they might be, what other personal or professional constraints we might know them to be under at any given time, etc. especially when those people or groups are not deeply embedded in radically visible FOSS-like processes otherwise.

So, this was probably always a bad fit for a public issue tracker.
