### ISSUE TITLE
Install WordPress instance for web presence

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#57]
# Summary

Install basic WordPress instance to get a short-term web presence up for FOSS@MAGIC

# Background

A WordPress site gives a quick and straightforward way to get a web presence up for us while we are waiting for other dust to settle. It offers flexible rules to allow multiple people to gain access and make contributions to the content. It also provides the easiest path to possibly "merging" back into a different WordPress installation once the future of the MAGIC website is determined.

# Details

This is blocked by #56. Once unblocked, the following needs to be done:

1. Install WordPress (with as much automated management as possible)
2. Add new users for @itprofjacobs and other FOSS@MAGIC staff, if necessary
3. Begin populating site with content (both pre-existing content and new content yet to be written)
4. Circulate / announce new website on FOSS mailing list

# Outcome

Gives FOSS@MAGIC a linkable, referenceable place to point interested people to learn more about us and what we do; lowers the barrier to contributing and making site content changes until final direction is decided

**Comment by jwflory** [comment]
#56 is now complete, so this ticket is unblocked.

I'm pairing with @nlMeminger to write an Ansible playbook to deploy a WordPress site to our infrastructure. The goal is to have a running and minimally configured WordPress site by the end of week (Friday, Sept. 21).

**Comment by nlMeminger** [comment]
Currently working on this.  Blocked on familiarizing myself with Ansible.  Progress is being made, and I am confident we can have this rolled out by Friday.

**Comment by nlMeminger** [comment]
Justin and I worked on this together tonight. We found an ansible playbook that was open sourced from ansible on deploying Wordpress, and copied it to the infrastructure repo. Need to spend some time together to update and took the playbook to our needs.

**Comment by jwflory** [comment]
Moving this back. I'm overloaded this week and focusing my efforts at #66 and #71 for Maker Faire prep.

**Comment by jwflory** [comment]
Abandoning WordPress in favor of FOSSRIT/fossrit.github.io#12.
