### ISSUE TITLE
Organize and Prune The Dan Dump

### ISSUE THREAD

**Issue by itprofjacobs** [FOSSRIT/tasks#62]
# Summary

# Background

# Details

# Outcome

**Comment by jwflory** [comment]
Pinging for follow-up – did you have a chance to work on this yet, @itprofjacobs?

**Comment by jwflory** [comment]
@itprofjacobs is halfway through the data dump. Time is blocked aside for this on Monday, Oct. 1st. Will follow-up at Wednesday, Oct. 3 meeting.

**Comment by jwflory** [comment]
_Discussed in 2018-10-03 meeting._

---

Progress made but not yet complete. @itprofjacobs going to work on it over the weekend and while traveling next week. Will follow up on 2018 Oct. 17.

**Comment by jwflory** [comment]
Moving this to backlog. May wait until after break. It's a big undertaking.

**Comment by jwflory** [comment]
* @itprofjacobs to follow-up at next week's meeting
* Useful to consider design assets we can recycle (see #81)

**Comment by jwflory** [comment]
I made some dents on this over the last week or two. I'm going to close this issue as complete. We can revisit with specific, targeted goals if the existing organization is insufficient.

Closing as complete. :clapper:
