### ISSUE TITLE
Prepare for Mel Chua FOSS Talk

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#64]
# Summary

Set up infrastructure and update printed promotional materials for @mchua's FOSS Talk on **Monday, Sept. 24**

# Background

@mchua is delivering a FOSS Talk on Monday, Sept. 24. We need to start promoting her session and getting infrastructure in place for the FOSS Talk.

# Details

- [x] Set up EventBrite form to collect RSVPs for ordering food
- [x] Promote EventBrite on all RIT FOSS community mailing lists
- [x] Update the FOSS Talk poster from file dump (#62)
- [x] Send to @itprofjacobs + Brenda for approval and request for printing (quantity based on how many people we can recruit to hang posters)

# Outcome

@mchua has an awesome FOSS Talk on Monday, Sept. 24, people come to see it, people have an all-around good time :tada:

**Comment by jwflory** [comment]
An [Eventbrite form](https://www.eventbrite.com/e/foss-talks-universe-hacking-how-the-open-source-way-can-remake-our-realities-tickets-50381970831) is now created, pending final approval before sending out more widely.

I am having battles in Inkscape to get the old Illustrator file working (found [here](https://github.com/FOSSRIT/brand/blob/master/events/foss-talks/mel-chua/foss-talk-mel-chua-poster.ai)). I'll try to work with a lab computer to make the edits in the short-term.

**Comment by ritjoe** [comment]
On Mon, Sep 17, 2018 at 05:27:24PM -0700, Justin W. Flory wrote:
> An Eventbrite form is now created, pending final approval before sending out
> more widely.
> 
> I am having battles in Inkscape to get the old Illustrator file working (found
> here). I'll try to work with a lab computer to make the edits in the
> short-term.

Do you have access to a workstation somewhere with a license for the legacy proprietary software that handles that format, and that might be able to export or "save as" a format more amenable to use in Inkscape et al?

**Comment by jwflory** [comment]
> _**@ritjoe wrote…**_
> Do you have access to a workstation somewhere with a license for the legacy proprietary software that handles that format, and that might be able to export or "save as" a format more amenable to use in Inkscape et al?

I'm hoping to get my hands on an IST lab computer with a recent version of Illustrator to get it into an Inkscape-workable format. :slightly_smiling_face:

**Comment by nlMeminger** [comment]
> > _**@ritjoe wrote…**_
> > Do you have access to a workstation somewhere with a license for the legacy proprietary software that handles that format, and that might be able to export or "save as" a format more amenable to use in Inkscape et al?
> 
> I'm hoping to get my hands on an IST lab computer with a recent version of Illustrator to get it into an Inkscape-workable format. slightly_smiling_face

I'm pretty confident that the IST lab computers have illustrator, but if they do not I would suggest trying one of the College of Arts labs or the libray

**Comment by jwflory** [comment]
The email announcement was sent out to the fossrit, floss-seminar, and ritlug-announce mailing lists. I'm leaving this issue open pending printed posters to hang up this week.

**Comment by jwflory** [comment]
Attendee list sent for accounting purposes to MAGIC. Successfully held FOSS Talk this past Monday. Thanks @mchua for the awesome presentation.

Closing as complete. :clapper:
