### ISSUE TITLE
Update Remybook laptop to something not EOL

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#71]
# Summary

Get the Remybook laptop updated to latest Fedora to use at upcoming Maker Fair (#55)

# Background

We want to use it again but it's woefully out-of-date. Need to get it up to speed.

# Details

@wilfriedE was the last person to use the laptop. Should check in with him first to make sure nothing of value is on laptop. Will probably go for full system wipe.

# Outcome

Laptop can be used for FOSS@MAGIC events (e.g. Maker Faire)

**Comment by ct-martin** [comment]
TigerOS hopes to release with f29 in a couple weeks if you want to consider using that. I also have a couple magic USB drives that tend to work on devices that should be able to boot from USB but like to be difficult if your want to borrow them.

**Comment by wilfriedE** [comment]
@jwflory I can confirm that there is nothing of value on it.

**Comment by jwflory** [comment]
Since Imagine RIT is coming up, I took care of this today. The Remybook is now running CentOS 7.6. It is provisioned and ready for use in SJ's office.

Closing as complete. :clapper:
