### ISSUE TITLE
Plan for FOSS@MAGIC presence at Imagine RIT 2019

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#79]
# Summary

Plan and execute a FOSS@MAGIC table at [Imagine RIT](https://www.rit.edu/imagine/) 2019

# Background

Each year, FOSS@MAGIC participates at the Imagine RIT 2019 showcase at RIT's campus. We use this as an outreach opportunity to demo student work and talk about things happening in our community. For our table, we need 2-4 projects to bring with us to demo at our table.

It's also a good idea to look at getting brochures to include on the table and possibly other swag (e.g. stickers).

# Details

The following table shows potential projects and who is leading the project:

| Project name                                        | Project lead                       | Confirmed? |
| ------------------------------------------------ | --------------------------------- | --------------- |
| MAGIC/FOSS letters                            | @nlMeminger                    | Yes              |
| Arduino heart rate sensor watch          | @hunaina100                    | Yes              |
| Magic mirror                                         | @nlMeminger (hardware) | Yes               |

# Outcome

We have an awesome table to talk up what we're doing all semester, we meet cool new people, see old friends, make new connections… all good stuff!

**Comment by jwflory** [comment]
## Organizing projects

* Continue organizing projects and finding volunteers for Imagine RIT
* Need to work on text blurb of our exhibit
* Need to get commitments for volunteers for the FOSS@MAGIC booth at Imagine
  * Likely need to plan shifts because of varying volunteers 

## Paperwork application

* Paperwork currently **blocked**
* No need to apply to university – we apply to MAGIC (via Jenn)
* Be ready to act once MAGIC starts planning for Imagine

**Comment by Tjzabel** [comment]
In the same vein, is FOSS@MAGIC planning on doing another joint table with RITlug?

**Comment by jwflory** [comment]
@Tjzabel I confirmed with @itprofjacobs. RITlug can exhibit alongside FOSS@MAGIC in MAGIC Spell Studios. If going this route, RITlug should apply through MAGIC and _not_ RIT. I suggest emailing `Jennifer.Hinton at rit dot edu` and SJ to coordinate this.

**Comment by jwflory** [comment]
Our application to Imagine is submitted and complete as of 2019-02-20. Next steps are to follow-up with our projects as Imagine comes closer.

**Comment by jwflory** [comment]
@nlMeminger Do you have any updates about the FOSS letters? Anything me or @itprofjacobs can do to help you?

**Comment by nlMeminger** [comment]
The 3D models are near completetion.

**Comment by nlMeminger** [comment]
The 3D models for all the letter are now done and I am ready to start printing after approval from SJ.  This is blocked however on the Construct@rit until they get their new large-format 3D printer in about two weeks.  Once that is in I can start printing, and it will take about a week to print everything.

**Comment by jwflory** [comment]
Hi @hunaina100! Could you share a few sentences about your Arduino project as a comment in this GitHub issue? This will help bring everyone in sync on what we will have on our Imagine table this year. :smile:

**Comment by hunaina100** [comment]
I will definitely do that!

**Comment by jwflory** [comment]
Imagine RIT wrapped up yesterday. :clapper: Some pictures found at this tweet:

https://twitter.com/RITlug/status/1122196944212905984

Thanks everyone for your help and participation to make this year's exhibit possible. :tada:
