### ISSUE TITLE
Validate IGME-585 offering for 2191 semester

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#82]
# Summary

Ensure IGME-585 Projects in FOSS Development is offered in Fall 2019 (2191) semester

# Background

The course did not roll over to next fall automatically. There is ongoing work by @itprofjacobs to get it into the registrar. @ritjoe is also providing support with @itprofjacobs to solve this problem in the long-term.

# Details

Success criteria to close this issue is when IGME-585 appears in SIS / TigerCenter.

# Outcome

* Students can start enrolling in IGME-585 when shopping carts open
* We start promoting the course with set dates/times

**Comment by jwflory** [comment]
@itprofjacobs @ritjoe IGME-585 does not appear in the registry yet. Is there any follow-up we should do here?

**Comment by jwflory** [comment]
@itprofjacobs @ritjoe I still don't see a course offering yet for IGME-585. Enrollment for fall opens soon. Any updates on this?

**Comment by jwflory** [comment]
I confirmed IGME-585 is listed in Fall 2019 taught by @ritjoe and IGME-582 is listed in Spring 2020 with a TBA instructor:

## Fall 2019

![IGME-585 Projects in FOSS Development course listing in TigerCenter for Fall 2019 semester](https://user-images.githubusercontent.com/4721034/55368915-433d7300-54c2-11e9-92b8-7e86dc43b9ef.png "IGME-585 Projects in FOSS Development course listing in TigerCenter for Fall 2019 semester")

## Spring 2020

![IGME-582 Humanitarian FOSS Development course listing in TigerCenter for Spring 2020 semester](https://user-images.githubusercontent.com/4721034/55368961-74b63e80-54c2-11e9-85a7-b87e9f404ec9.png "IGME-582 Humanitarian FOSS Development course listing in TigerCenter for Spring 2020 semester")

---

Closing ticket as complete. :clapper:

**Comment by ritjoe** [comment]
Should be other way round: Spring IGME-582 HFOSS Dev with me.

On Mon, Apr 01, 2019 at 06:10:23PM -0700, Justin W. Flory wrote:
> I confirmed IGME-585 is listed in Fall 2019 taught by @ritjoe and IGME-582 is
> listed in Spring 2020 with a TBA instructor:
> 
> Fall 2019
> 
> IGME-585 Projects in FOSS Development course listing in TigerCenter for Fall
> 2019 semester
> 
> Spring 2020
> 
> IGME-582 Humanitarian FOSS Development course listing in TigerCenter for Spring
> 2020 semester
> 
> ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
> 
> Closing ticket as complete. 🎬
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.*
> 

-- 
-- 
Joe   On ceding power to tech companies: http://xkcd.com/1118/
man screen | grep -A2 weird
  A weird imagination is most useful to gain full advantage of
  all the features.

**Comment by jwflory** [comment]
@ritjoe SJ and I assumed this was the case, but the instructor details should be easier to swap. I think @itprofjacobs is still waiting on his course assignment for the fall semester. We can follow-up on our Wednesday morning meeting. :+1:
