### ISSUE TITLE
Design new Minor in FOSS posters to promote courses

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#83]
# Summary

Work with MAGIC Center student employees to design new poster to promote _Minor in FOSS_ posters with course information

# Background

[Previous posters](https://www.dropbox.com/sh/5r7v5aq8nnxc1pl/AADXjjaThHedPD0WWO_ssA_1a?dl=0) were designed for the courses. But there issues with color choice and general readability last time we printed. Updating the design to improve readability would help.

The **primary goal** is to create a reusable template for these things where we can quickly expedite the creation of new posters on short notice. Ideally, the only information we need to change across semesters is adding/removing copytext for some courses and updating dates/times.

# Details

Last year's posters are available in Dropbox [here](https://www.dropbox.com/sh/5r7v5aq8nnxc1pl/AADXjjaThHedPD0WWO_ssA_1a?dl=0). Next step is for @itprofjacobs to reach out internally to get an updated design.

# Outcome

* More sustainable promotion of FOSS courses each semester (i.e. less overhead to get these posters up)
* Better promotion of FOSS courses _next_ semester

**Comment by jwflory** [comment]
Email follow-up made on Feb. 27th.

**Comment by jwflory** [comment]
@itprofjacobs Did you reach out to the MAGIC design student(s) about the posters? Can I do anything to help with this?

**Comment by jwflory** [comment]
A PDF and Adobe Illustrator file are available with the poster. Uploading the rendered PDF here for now:

[FOSS poster](https://github.com/FOSSRIT/tasks/files/3013526/FOSS.copy.pdf)

**Comment by jwflory** [comment]
I need to add two courses to Fall 2019 and three courses for Spring 2020. I'm not sure what I should highlight for the Year in FOSS poster. cc: @itprofjacobs @ritjoe 

* Fall 2019:
  * ENGL-450
  * IGME-585
* Spring 2020:
  * IGME-582

**Comment by jwflory** [comment]
This isn't going to happen for next semester, but we should keep this open until we have a mechanism in place to get these posters updated on short notice.

**Comment by ritjoe** [comment]
Is there an editable version of this file, and if so, where? Can it be attached to this issue?

**Comment by jwflory** [comment]
Fortunately I was able to dig it up. Sorry for the delay. Here is the Adobe Illustrator file.

[foss-poster-march-2019.zip](https://github.com/FOSSRIT/tasks/files/3419967/foss-poster-march-2019.zip)

**Comment by whenbellstoll** [comment]
Here is the SVG format of the poster so it can be opened in Inkscape

[foss-poster-march-svg-2019.zip](https://github.com/FOSSRIT/tasks/files/3611279/foss-poster-march-svg-2019.zip)

**Comment by jwflory** [comment]
@whenbellstoll Thanks! I started porting the poster over to free fonts and to work out some of the kinks in Inkscape. I'm going to mark this for follow-up with @itprofjacobs to get a list of courses we want to promote in relation to FOSS academia next semester. I will finish porting the poster over and commit it to our brand repo once I know which classes to fill in for next semester.

**Comment by jwflory** [comment]
I tagged most folks involved in the new PR, but see PR FOSSRIT/brand#7. I added the SVG I have so far to the brand repo since I'm leaving RIT in a couple more weeks. That PR closes this issue out until we are ready to produce another poster.
