### ISSUE TITLE
Planning a one-day conference to teach and promote FOSS in Fall 2019

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#84]
# Summary

Evaluate running a one-day conference to introduce FOSS, host a panel with alums, and run small breakout sessions to teach and promote FOSS

# Background

@itprofjacobs suggested a panel with alums from the FOSS program to talk about their experiences with open source and how it impacted their career. It expanded to an idea of running a mini day-conference to introduce FOSS at RIT and include the panel.

## Timeline

* End of September (before Career Fair; Saturday, Oct. 26)
* 1/2 or full-day on Saturday

# Details

To consider this, we need to answer these questions:

1. What themes / topics do we want to focus on?
2. What is the goal / scope of the conference?
3. Who can we try to partner with to make this a success?

The most important thing to drill down is scope for what we will do and not do. Since this is a new idea, it is better to err on the side of under-promising and over-delivering.

We also want to solicit interest from the RIT FOSS community if this is something they would be interested in!

# Outcome

* Better introduction to FOSS@MAGIC, our program, and ways to get involved, especially for new students
* Connecting past alums with today's students to see all the cool stuff our awesome alums are doing
* Building intersectional relationships with other communities at RIT
* (Hopefully) a great opportunity to announce a new FOSS immersion!

**Comment by nic-hartley** [comment]
I'm all for this idea! I'm curious about future plans -- if all goes well with this one, is making it a recurring conference on the table? Or will it be a one-time event?

**Comment by jwflory** [comment]
@nic-hartley The idea is we would try it out for the first time and see how it goes. If it's successful, we might make this an annual, recurring event.

**Comment by itprofjacobs** [comment]
What Justin said :-)

**Comment by jwflory** [comment]
_Discussed in 2019-04-10 weekly FOSS@MAGIC meeting._

---

* **Date**: October 12 2019

Next steps to pull this event off:

* Determine tracks for what kind of content we want to encourage / focus on
* Create a Call for Proposals (CfP) for students, faculty, and alums to submit ideas or content
  * Should open mid-May and close mid-June (i.e. not until graduation passes)
* Marketing / call-to-action:
  * FOSS@MAGIC blog post
  * Mailing lists / shoulder taps

**Comment by WillNilges** [comment]
Hi, I'm Will from CSH! I'm super interested in making this happen. Recently, I've begun planning a Linux install-a-thon with RITLUG, and I think it'd be cool to host an instance of it at this conference, if you want to have some interactive activities with this. What are you guys thinking for break-out sessions.

**Comment by jwflory** [comment]
@WillNilges Thanks for your interest and patience. I think an install-a-thon activity would be a good break-out session for this event. Our rough plan for now is to open a Call For Proposals in June. We would begin to fill out a schedule based on who applies. We'll keep you updated with more info as planning progresses.

**Comment by jwflory** [comment]
## 2019-05-16 minutes

### Attendees

* @itprofjacobs
* @jwflory 
* @Nolski
* @whenbellstoll

### Notes

* **Conference title**: The Future is Open (pending approval)
* Save-the-date / CFP by end of day announced on Tuesday, 21 May
  * @whenbellstoll to have CFP Google Form ready for review by end of Friday, 17 May
* Suggested tracks:
  * **Open source research (_faculty_)**: Faculty presenting open source research they are working on (e.g. NTID building open source for [deafworldaroundyou.org](https://deafworldaroundyou.org/)
  * **Panels (_beginning/end_)**
  * **Student / club projects**
  * **Everything else**: We could break this down into smaller categories depending on what submissions we get
* **CFP close date**: Friday, Aug. 2
* **CFP notification date**: Friday, Aug. 30

[Example CFP from Linux Foundation](https://events.linuxfoundation.org/events/open-source-in-gaming-day-2019/program/call-for-proposals-cfp/)

[RIT academic calendar](https://www.rit.edu/calendar

**Comment by whenbellstoll** [comment]
### CPF Form Progress
I've been working on the CFP form this afternoon, here is that link:
[CFP Form](https://docs.google.com/forms/d/1_dCtVi1b57yDO4ukF6yy_bu62sh8-SCy97kcQ5Um2MU/edit)
Of course it still has some work to be done, but it's a start. We can go over it in the meeting tomorrow.
