### ISSUE TITLE
UNICEF Identify Success Criteria

### ISSUE THREAD

**Issue by whenbellstoll** [FOSSRIT/tasks#85]
# Summary

Identify and organize a set of items and actions to measure the Open Source success of the UNICEF Innovation teams.

# Background

As of now, UNICEF does not have an identifiable idea of what the requirement of "Open Source" means within the context of the Innovation Fund. This is the problem we are addressing.

# Details

- Create outline
- Identify requirements
- Identify Pass/ Fail of requirements

# Outcome

To have actionable criteria for teams to adapt to Open Source and the ability to measure their success.

**Comment by jwflory** [comment]
Together, @whenbellstoll, @Nolski, and I finished up on the [success criteria](https://docs.google.com/document/d/1A6K7zKLlEdt5HgP351weECYt2ZYjmlmq08ZH2zScAVA/edit?usp=sharing) to evaluate open source projects. It is still a rough draft, but we'll use this to inform the rubric we are creating.

Once we get a final round of feedback on the document after our next meeting on 17 May, 16:30 US EDT.

**Comment by whenbellstoll** [comment]
We have finished the draft of the success criteria, and moving forward with integrating it with the project rubrics.
This closes [Issue #85](https://github.com/FOSSRIT/tasks/issues/85)
