### ISSUE TITLE
Announce "The Future is Open" and launch CfP

### ISSUE THREAD

**Issue by jwflory** [FOSSRIT/tasks#93]
# Summary

Create a blog post announcement and open a Call for Proposals for the first _The Future is Open_ conference in October 2019

# Background

Related to #84.

We have selected final dates and are ready to open a call for proposals (CfP) for the conference. The next step is to get the word out. @whenbellstoll is working on a blog post announcement to publish on our website along with a CfP form to start collecting proposals.

# Details

1. Draft blog post announcement
2. Test it with Jekyll before publishing
3. Merge pull request on FOSSRIT/fossrit.github.io on Tuesday, May 21

# Outcome

* Start building the hype for the mini-conference
* Start collecting proposals for what content we will feature

**Comment by whenbellstoll** [comment]
@ritjoe Hey we were working on the Call for Proposals today, we have a draft for the announcement, if you wanted to take a look at that and give some feedback [link here](https://github.com/FOSSRIT/fossrit.github.io/blob/CFPannouncement/announcements/_posts/2019-05-21-cfp-announcement.md)

**Comment by whenbellstoll** [comment]
The article has been published on fossrit.github.io and the form is available to fill out, closing the issue
