### ISSUE TITLE
UNICEF High Level Team Evaluations

### ISSUE THREAD

**Issue by whenbellstoll** [FOSSRIT/tasks#96]
# Summary
Create a high level rubric.

# Background
There is a need for an at-a-glance progress report of the teams for the reference of everyone. Our current rubric is specific to certain topics, we need a quick report.

# Details

- Spreadsheet in Google Sheets
- Use color system, no details
- Link to in-depth rubrics on each topic
- Give a color report for each category,
- Give a color report for each topic
- Format teams and score with appropriate column spacing.

# Outcome

When this is complete we will have a quick way to measure the team's progress.

**Comment by whenbellstoll** [comment]
Progress made today, I've made a rubric that I'm happy with, if @Nolski @itprofjacobs and / or @jwflory want to overview, give feedback, make suggestions, or give the thumbs-up I'd greatly appreciate it!

**Comment by itprofjacobs** [comment]
Send me a direct link and I’ll review in my morning while you’re asleep :-)

**Comment by whenbellstoll** [comment]
> Send me a direct link and I’ll review in my morning while you’re asleep :-)
> […](#)
> On May 20, 2019, at 10:40 PM, Kent Reese ***@***.***> wrote: Progress made today, I've made a rubric that I'm happy with, if @Nolski @itprofjacobs and / or @jwflory want to overview, give feedback, make suggestions, or give the thumbs-up I'd greatly appreciate it! — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Made an edit to my original comment after realizing I never linked it, and posting it [here](https://docs.google.com/spreadsheets/d/1jfWrgw_cgxOobrO8Wy4fTm2S9hILO-4QqXYBrZPH5pc/edit#gid=0)

**Comment by Nolski** [comment]
Great Job @whenbellstoll! This is looking really good. A few quick questions/comments/suggestions for future iterations:

1.  It'd be great to see how teams are improving over time. I wonder if there's a more machine friendly way to show this. Like a dashboard of some sort being powered by a spreadsheet. ([redash](https://github.com/getredash/redash) comes to mind)
2. I love the color coding here. A legend might be worthwhile just to describe what each color means.
3. I think it might be worthwhile to have a small text section for each team that will allow us to interject any findings around progress that don't fit in to our existing metrics.
4. Lastly, Links to the resources (project board, issue tracker, code of conduct, etc.) when they receive a green or (where applicable) yellow will be really useful as well but perhaps this is what issue #92  is about.

**Comment by itprofjacobs** [comment]
Hi Nolski!

> On May 21, 2019, at 8:47 AM, Mike Nolan <notifications@github.com> wrote:
> 
> Great Job @whenbellstoll <https://github.com/whenbellstoll>! This is looking really good. A few quick questions/comments/suggestions for future iterations:
> 
> It'd be great to see how teams are improving over time. I wonder if there's a more machine friendly way to show this. Like a dashboard of some sort being powered by a spreadsheet. (redash <https://github.com/getredash/redash> comes to mind)
It would be good to standardize across cohorts to use something like this.
In fact I did suggest the creation of an at a glance dashboard with the guys Friday.  Might be beyond Kent’s current chops.  You up to it? 
I was thinking each major topic’s overall color (meter, pie chart whatever) be a reflection of each of the sub topics, and that each subtopic be clickable so that you could open a more detailed set of data/report on it’s status.

It’ll be useful to help us determine where cohorts are having common problems and perhaps doing joint calls  or creating docs to address those issues.

> I love the color coding here. A legend might be worthwhile just to describe what each color means.
+1
> I think it might be worthwhile to have a small text section for each team that will allow us to interject any findings around progress that don't fit in to our existing metrics.
+1
> Lastly, Links to the resources (project board, issue tracker, code of conduct, etc.) when they receive a green or (where applicable) yellow will be really useful as well but perhaps this is what issue #92 <https://github.com/FOSSRIT/tasks/issues/92> is about.
+1

**Comment by Nolski** [comment]
I think having an online dashboard would definitely be worthwhile and setting up a process that's automated is worthwhile. I'm happy to make an issue for it but want to prioritize setting up a plan for these cohorts first.

In the mean time, I think we can do something similar fairly easily by re-formatting or having a second sheet on the google docs. I made an example sheet which on the google doc @whenbellstoll  created that is essentially formatted the same but over time. We can copy paste that same format for each team as well.

**Comment by whenbellstoll** [comment]
Thanks for the feedback!

> 1. It'd be great to see how teams are improving over time. I wonder if there's a more machine friendly way to show this. Like a dashboard of some sort being powered by a spreadsheet. ([redash](https://github.com/getredash/redash) comes to mind)
+1 As SJ already said, 


> 2. I love the color coding here. A legend might be worthwhile just to describe what each color means.
+1 Already on it.

> 3. I think it might be worthwhile to have a small text section for each team that will allow us to interject any findings around progress that don't fit in to our existing metrics.
+1 Done.

> 4. Lastly, Links to the resources (project board, issue tracker, code of conduct, etc.) when they receive a green or (where applicable) yellow will be really useful as well but perhaps this is what issue #92  is about.
+1 The implementation of this isn't in the github issues yet, I'll make a new one, but the way Justin, SJ, and I had talked about it was that I would make the [topic rubrics](https://drive.google.com/drive/folders/1b90HJ0hBm2qMpYO99QKIUhtdEQtExt_I) linking to them from this document.

**Comment by whenbellstoll** [comment]
Given that the improvements have been implemented and the only thing left to do is link this and the [Topic Rubrics](https://github.com/FOSSRIT/tasks/issues/97) this issue can finally be closed.
