### ISSUE TITLE
UNICEF / LibreCorps Connect High Level Rubric with Topic Rubric

### ISSUE THREAD

**Issue by whenbellstoll** [FOSSRIT/tasks#97]
# Summary

This is a detailing of the relation between issues [#86](https://github.com/FOSSRIT/tasks/issues/86) and [#96](https://github.com/FOSSRIT/tasks/issues/96).  

# Background

The High Level Rubric needs access to higher detail from the topics listed for each team. This issue explains how this will be done.

# Details

- Get issues [#86](https://github.com/FOSSRIT/tasks/issues/86) and [#96](https://github.com/FOSSRIT/tasks/issues/96) done in their own right.
- Send the rubrics to the teams
- Once the teams start self-evaluating we will start to inform the High Level Rubric, factoring in our own evaluations as well.
- We link to the topic rubrics from the high level rubric

# Outcome

We will have an easy-to-access overview of the team's progress as well as an easy way to get more detailed information.

**Comment by Nolski** [comment]
@whenbellstoll I think this issue can be closed now that the rubric is consolidated into one document right?

**Comment by whenbellstoll** [comment]
@Nolski not yet, have to make rubrics for the teams and then link them to the high level one

**Comment by Nolski** [comment]
Ah right, I misunderstood the ticket. Sounds good :+1:

**Comment by jwflory** [comment]
Migrated to librecorps/tasks#10. Closing.
