### ISSUE TITLE
UNICEF VR Cohort Preliminary Phone Call Interviews

### ISSUE THREAD

**Issue by Nolski** [FOSSRIT/tasks#98]
# Summary

Contact each VR team to get a general idea of where they are in integrating FOSS into their projects. 

# Background

As of now, it's unclear where the teams are in the process, generally it's assumed that they're still early on, but we need direct communication to get a clear idea.

# Details

- Identify what the teams have done so far.
- Where they think they need help.
- Start brainstorming next steps*

# Outcome

We get a better idea of the progress and needs of the VR teams.

**Comment by Nolski** [comment]
Hey @whenbellstoll, would you mind scheduling the calls for these companies?

**Comment by whenbellstoll** [comment]
Setup the intro call with Nubian VR, sending the reach out email to the rest of the VR cohorts today.

**Comment by whenbellstoll** [comment]
I made contact with all of the VR cohorts today, whether or not they had reached out.

**Comment by Nolski** [comment]
@whenbellstoll So we have made contact with all of the VR cohorts and have just 1 left correct?

**Comment by whenbellstoll** [comment]
We have three calls left, one reached out today, one failed to get back after an initial email they sent back and responded, and one I failed to contact after an initial email.
